#
# Review pipeline. Run build and deploy for Platta dev environments.
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
# only PR trigger pipeline
trigger: none

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to 
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a 
# merge commit, which is the merged code between the source and target branches 
# of the pull request.
#
# Opt out of pull request validation 
pr:
  # PR target branch
  branches:
    include:
    - main
  paths:
    exclude:
    - '*release-please*'
    - '*.md'
    - '.github/'
    - 'sources/'
    - 'pipelines/unified-search-graphql-release.yml'
    - 'pipelines/unified-search-graphql-dev.yml'
    - 'pipelines/unified-search-sources*'
    - '*compose*'

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: kuva-unified-search-pipelines
      type: git
      ref: refs/heads/ansible_automation_update
      # Azure DevOps project/repository
      name: kuva-unified-search/kuva-unified-search-pipelines

extends:
  # Filename in Azure DevOps Repository
  template: components/unified-search-graphql/pipelines/unified-search-graphql-review.yml@kuva-unified-search-pipelines
  # parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments or configMap values, the rest located in kuva-unified-search-pipelines
    # The values here will override the values defined in the kuva-unified-search-pipelines repository
    # buildArgs:
    #   DEBUG: 1
    # configMap: # pod environment variables
    #   DEBUG: 1
