"""
Django settings for sources project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from datetime import datetime
from pathlib import Path

import sentry_sdk
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration

from .csp_settings import CONTENT_SECURITY_POLICY  # noqa: F401

# Load environment variables from .env in current directory or higher.
#
# From https://github.com/theskumar/python-dotenv?tab=readme-ov-file#getting-started
#
# "By default, load_dotenv doesn't override existing environment variables
# and looks for a .env file in same directory as python script or searches
# for it incrementally higher up."
load_dotenv()

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN", ""),
    environment=os.getenv("SENTRY_ENVIRONMENT", ""),
    integrations=[DjangoIntegration()],
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# ES_URI environment variable can be a comma-separated list of URIs, or a single URI:
ES_URI = [uri.strip() for uri in os.getenv("ES_URI", "").split(",")]
ES_USERNAME = os.getenv("ES_USERNAME", "")
ES_PASSWORD = os.getenv("ES_PASSWORD", "")

DEBUG = os.getenv("DEBUG", "false").lower() in ("yes", "true", "t", "1")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "csp",
    "health_check",
    "custom_health_checks",
    "munigeo",
    "ingest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sources.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sources.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.spatialite",
        "NAME": BASE_DIR / "db_data" / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATIC_ROOT = os.getenv("STATIC_ROOT", os.path.join(BASE_DIR, "static"))

LOGGING = {
    "version": 1,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            # StreamHandler outputs to stderr by default, see
            # https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        # Root logger
        "": {
            "handlers": ["console"],
            "propagate": True,
            "level": "DEBUG" if DEBUG else "INFO",
        },
        "django.request": {
            "handlers": ["console"],
            "propagate": False,
            "level": "DEBUG" if DEBUG else "WARNING",
        },
        "elasticsearch": {
            "handlers": ["console"],
            "propagate": False,
            "level": "DEBUG" if DEBUG else "WARNING",
        },
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Release/build information:
APP_RELEASE = os.getenv("APP_RELEASE")
APP_COMMIT_HASH = os.getenv("APP_COMMIT_HASH")
APP_BUILD_TIME = datetime.fromtimestamp(os.path.getmtime(__file__))

# django-cors-headers settings:
# https://github.com/adamchainz/django-cors-headers/tree/4.7.0?tab=readme-ov-file#configuration
#
# This is a very permissive CORS configuration,
# which is suitable because only readiness/healthz endpoints are available,
# see sources/sources/urls.py for available endpoints.
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for readiness/healthz endpoints
CORS_ALLOW_CREDENTIALS = False  # Forbid cookies in cross-site requests
CORS_ALLOW_METHODS = ["GET", "HEAD"]  # Only for readiness/healthz endpoints
